### ISSUE TITLE
Class overlay

### ISSUE THREAD

**Issue by dermotbalson** [loopspace/Codea-Shapes#2]
I think it will be sufficient to just have a Jewel and Box object in the class overlay, and users can simply add whatever features they want, pretty much as you have them.

I'll upload an updated class tomorrow with most of the features built in.

I don't think we should spend too much time on all this, as there is more interesting stuff to work on.

**Comment by loopspace** [comment]
I've given you "collaborator" status on this repository which should mean that you can commit to it and upload your class overlay file.  We'll see how if this workflow works for us.

**Comment by dermotbalson** [comment]
I've updated my class for spheres, and tested with an actual world map, as shown below

https://www.youtube.com/watch?v=ycH8bQoyahI

The class is a pretty shallow overlay on your code. Your documentation helps a great deal, thanks for that.

I've uploaded my class code (commenting out the world map part because you don't have the image)
