### ISSUE TITLE
Other shapes

### ISSUE THREAD

**Issue by dermotbalson** [loopspace/Codea-Shapes#3]
The library has a jewel and a deformable cube/block

Can we easily add the pipe/cylinder you had before? A sphere? What about those other parametric shapes? If it's easy, let's add some variety for the users.

I don't want to spend too much time on this library, but two shapes aren't going to get anyone too excited.

**Comment by loopspace** [comment]
The latest commit from me included a sphere (which can be deformed into an ellipsoid) and a sphere segment.  Next on the list is a cylinder, and cylinder segment.  These can the form the backbone of a tube.

**Comment by loopspace** [comment]
Cylinder (and cylinder segment) now implemented as of 121d920763b0745e24ce36787e47e0163d4e7795
