### ISSUE TITLE
Pyramid

### ISSUE THREAD

**Issue by dermotbalson** [loopspace/Codea-Shapes#4]
I managed to create a pyramid using the cube code, but it is on its side pointing into z, because the start and end faces you use to draw a block are on the z axis rather than the y axis

**Comment by loopspace** [comment]
The `startwidth` and so forth can be vectors which overrides the default direction.  But anyway, a pyramid would be more efficient as a separate shape as it has only half the triangles of a cube.

**Comment by loopspace** [comment]
I've implemented a pyramid shape in 121d920763b0745e24ce36787e47e0163d4e7795
