### ISSUE TITLE
Cylinder segment ends

### ISSUE THREAD

**Issue by loopspace** [loopspace/Codea-Shapes#6]
For a cylinder, the options are as to whether to fill in the ends; for a segment of a cylinder, does that still make sense?  Or should it be like the sphere segment where the option is to make it solid or not?

**Comment by dermotbalson** [comment]
Again, I'm not fussed, do we even need this?

Who is going to use the segment of a cylinder?

**Comment by loopspace** [comment]
I've added a `solid` option which implies that the ends are also drawn, but supplying `ends` will override this.

Fixed in b7a1a5df8a9d4b38c4d7326d43fb1e8601dec21a.
