### ISSUE TITLE
Sphere segment shape

### ISSUE THREAD

**Issue by loopspace** [loopspace/Codea-Shapes#8]
At the moment, the sphere segment joins up to the centre.  Should it look more like if you sliced a sphere along the given lines of latitude and longitude?

**Comment by dermotbalson** [comment]
I don't really have a view, except that I doubt that many people will use this particular shape (and care too much about its details), so I wouldn't go overboard

**Comment by loopspace** [comment]
I think it looks better sliced along lines of latitude and longitude so I've adjusted it accordingly (and sorted out the texture coordinates).

Incidentally, I use this shape to create joints between pipes.
